#cloud-config

package_update: true
package_upgrade: true

packages:
  - python3
  - python3-pip

runcmd:
  - pip3 install flask gunicorn
  - mkdir -p /opt/quoteapp
  - |
    cat > /opt/quoteapp/app.py <<EOF
    from flask import Flask
    import random

    app = Flask(__name__)

    quotes = [
        "It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
        "Not all those who wander are lost.",
        "It was the best of times, it was the worst of times...",
        "All animals are equal, but some animals are more equal than others.",
        "To the well-organized mind, death is but the next great adventure."
    ]

    @app.route("/quote")
    def quote():
        selected_quote = random.choice(quotes)
        return f"<h1>Hello you, here is your quote of the day: {selected_quote}</h1>"
    EOF
  - cd /opt/quoteapp
  - nohup gunicorn -w 2 -b 0.0.0.0:80 app:app &